module.exports = {
	// Auth
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

	//User
	SET_AVATAR: 'SET_AVATAR',

	// Header
	REFRESH: 'REFRESH',
	SEARCH: 'SEARCH',
	SET_MENU: 'SET_MENU',

	// WebSocket
	WS: 'wss://steemit.com/wspa'
};