export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_NO_COOKIE = 'LOGIN_NO_COOKIE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_LAST_USER_LIST = 'UPDATE_LAST_USER_LIST';
export const SET_APP_DETAILS = 'SET_APP_DETAILS';